[formatter.cpp]
command = "clang-format"
options = ["-i"]
includes = ["*.cpp", "*.hpp"]

[formatter.cmake]
command = "cmake-format"
options = ["-i"]
includes = ["CMakeLists.txt"]

[formatter.nix]
command = "alejandra"
options = ["-q"]
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["-w"]
includes = ["*.json",	"*.yml"]
