name: CMake

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install cmake-format
        run: pipx install cmakelang
      - name: Run cmake-format on all CMake files
        run: find . -name 'CMakeLists.txt' -exec cmake-format --check '{}' +
